# Generated by Django 5.0rc1 on 2023-12-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopLocated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('open', models.BooleanField()),
            ],
        ),
    ]
